/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.study.Interface;

import br.study.dao.DAO;
import br.study.dao.DBConnect;
import br.study.modelo.ManipularImagem;
import br.study.modelo.Products;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;

/**
 *
 * @author jonathalima
 */
public class FrmNewPage extends javax.swing.JFrame {
    FrmHome frmHome = new FrmHome();
    Products product = new Products();
    BufferedImage image;
    JFileChooser fc;
    File arquivo;
    DBConnect dbCon = new DBConnect();
    JScrollBar jsb;
    //static FileInputStream input;
    /**
     * Creates new form FrmNewPage
     */
    public FrmNewPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegister = new javax.swing.JLabel();
        CmbbCategory = new javax.swing.JComboBox<>();
        PurchasedYear = new javax.swing.JComboBox<>();
        CmbbSubCategory = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSendImage2 = new javax.swing.JButton();
        btnSendImage1 = new javax.swing.JButton();
        btnSendImage4 = new javax.swing.JButton();
        btnSendImage3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register product");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        lblRegister.setText("Registre o produto");

        CmbbCategory.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        CmbbCategory.setForeground(new java.awt.Color(4, 2, 2));
        CmbbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Escolha a categoria", "Animais e acessórios", "Músicas e hobbies", "Moda e beleza", "Para a sua casa", "Esportes", "Eletrônicos", "Imóveis","Veículos"}));
        CmbbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbbCategoryItemStateChanged(evt);
            }
        });

        PurchasedYear.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        PurchasedYear.setForeground(new java.awt.Color(4, 2, 2));
        String[] year = new String[52];
        year[0] = "Ano de aquisição";
        int ano = 1990;

        for(int i = 1; i < 52; i++) {
            year[i] = ano+"";
            ano++;
        }
        PurchasedYear.setModel(new DefaultComboBoxModel(year));

        CmbbSubCategory.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        CmbbSubCategory.setForeground(new java.awt.Color(4, 2, 2));
        CmbbSubCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Subcategoria"}));
        CmbbSubCategory.setEnabled(false);

        lblName.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lblName.setText("Nome");

        txtName.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtName.setAutoscrolls(false);

        lblDesc.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lblDesc.setText("Descrição");

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Lucida Sans", 0, 14));
        txtDesc.setRows(5);
        txtDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtDesc);
        txtDesc.setLineWrap(true);
        txtDesc.setWrapStyleWord(true);

        lblPrice.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lblPrice.setText("Preço");

        txtPrice.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtPrice.setAutoscrolls(false);

        lblImage.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lblImage.setText("Imagens");

        btnSave.setFont(new java.awt.Font("Ubuntu Mono", 0, 16)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Ubuntu Mono", 0, 16)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("* Clique para adicionar imagens");

        btnSendImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/study/Interface/Half-upload.png"))); // NOI18N
        btnSendImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendImage(evt);
            }
        });

        btnSendImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/study/Interface/Half-upload.png"))); // NOI18N
        btnSendImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendImage(evt);
            }
        });

        btnSendImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/study/Interface/Half-upload.png"))); // NOI18N
        btnSendImage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendImage(evt);
            }
        });

        btnSendImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/study/Interface/Half-upload.png"))); // NOI18N
        btnSendImage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendImage(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegister)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CmbbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(CmbbSubCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(PurchasedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSendImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSendImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSendImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSendImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblRegister)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PurchasedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbbSubCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblImage)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSendImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSendImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSendImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frmHome.setVisible(true);
        try {
            dbCon.conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        frmHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void CmbbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbbCategoryItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            if(this.CmbbCategory.getSelectedIndex() == 0) {
                this.CmbbSubCategory.setEnabled(false);
                this.CmbbSubCategory.setModel(new DefaultComboBoxModel<>(new String[] {"Escolha a subcategoria"}));
            }
            if(this.CmbbCategory.getSelectedIndex() > 0) {
                this.CmbbSubCategory.removeAllItems();
                this.CmbbSubCategory.setEnabled(true);
                this.CmbbSubCategory.setModel(new DefaultComboBoxModel(DAO.getSubCategory(this.CmbbCategory.getSelectedIndex())));
            }
        }
    }//GEN-LAST:event_CmbbCategoryItemStateChanged

    private void btnSendImage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendImage
        fc = new JFileChooser();
        int res = fc.showOpenDialog(null);
        
        if(res == JFileChooser.APPROVE_OPTION) {
            arquivo = fc.getSelectedFile();
            
            try {
                image = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath());//, 114, 88);
                
                if(evt.getSource() == btnSendImage1) 
                    btnSendImage1.setIcon(new ImageIcon(getClass().getResource("/br/study/Interface/ok_half.png")));
                if(evt.getSource() == btnSendImage2) 
                    btnSendImage2.setIcon(new ImageIcon(getClass().getResource("/br/study/Interface/ok_half.png")));
                if(evt.getSource() == btnSendImage3) 
                    btnSendImage3.setIcon(new ImageIcon(getClass().getResource("/br/study/Interface/ok_half.png")));
                if(evt.getSource() == btnSendImage4) 
                    btnSendImage4.setIcon(new ImageIcon(getClass().getResource("/br/study/Interface/ok_half.png")));
                JOptionPane.showMessageDialog(null, "Successfully Inserted");
            } catch (Exception e) {
                System.out.println("");
            }
        }
        
    }//GEN-LAST:event_btnSendImage

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       product.setNome(txtName.getText());
       product.setDescription(txtDesc.getText());
       if(!txtPrice.getText().equals(""))
        product.setPrice(Double.parseDouble(txtPrice.getText()));
       product.setCategory((String) CmbbCategory.getSelectedItem());
       product.setSubCategory((String) CmbbSubCategory.getSelectedItem());
       product.setPurchasedYear((String) PurchasedYear.getSelectedItem());
        try {
            product.setImage1(ImageIO.read(arquivo));
        } catch (IOException ex) {
            System.out.println(ex);
        }
       
       if(!product.isEmpty()) {
           try {
               DAO.insertBD(product);
           } catch (FileNotFoundException ex) {
               System.out.println(ex);
           } catch (IOException ex) {
               System.out.println(ex);
           }

        txtName.setText("");
        txtDesc.setText("");
        txtPrice.setText("");
        CmbbCategory.setSelectedIndex(0);
        CmbbSubCategory.setEnabled(false);
        CmbbSubCategory.setSelectedIndex(0);
        PurchasedYear.setSelectedIndex(0);
        JOptionPane.showMessageDialog(null, "Successfully Saved");
       } else {
           JOptionPane.showMessageDialog(null, "Existem campos obrigatorios não preenchidos\n Porfavor preencher e tentar novamente");
       }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescMouseClicked
        
    }//GEN-LAST:event_txtDescMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNewPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbbCategory;
    private javax.swing.JComboBox<String> CmbbSubCategory;
    private javax.swing.JComboBox<String> PurchasedYear;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSendImage1;
    private javax.swing.JButton btnSendImage2;
    private javax.swing.JButton btnSendImage3;
    private javax.swing.JButton btnSendImage4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
