/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.study.Interface;

import br.study.dao.DAO;
import br.study.modelo.ManipularImagem;
import br.study.modelo.Products;
import java.awt.Image;
import java.awt.List;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathalima
 */
public class FrmSearch extends javax.swing.JFrame {
    String sql = null;
    DefaultListModel DML;
    Products product;
    ManipularImagem manImage = new ManipularImagem();
    /**
     * Creates new form FrmSearch
     */
    public FrmSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBusca = new javax.swing.JLabel();
        txtByName = new javax.swing.JTextField();
        txtByPrice = new javax.swing.JTextField();
        cbByCategory = new javax.swing.JComboBox<>();
        cbBySubCategory = new javax.swing.JComboBox<>();
        cbByYear = new javax.swing.JComboBox<>();
        btnBuscarNome = new javax.swing.JButton();
        btnBuscarPreco = new javax.swing.JButton();
        btnBuscarCategoria = new javax.swing.JButton();
        btnBuscarSubcategoria = new javax.swing.JButton();
        btnBuscarAno = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblResultado = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResult = new javax.swing.JList<>();
        lblOBS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblResultNome = new javax.swing.JLabel();
        lblResultDesc = new javax.swing.JLabel();
        lblResultAno = new javax.swing.JLabel();
        lblResultFotos = new javax.swing.JLabel();
        lblSetNomeResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaSetDescResult = new javax.swing.JTextArea();
        lblSetAnoResult = new javax.swing.JLabel();
        lblSetImage4 = new javax.swing.JLabel();
        lblsetImage3 = new javax.swing.JLabel();
        lblSetImage2 = new javax.swing.JLabel();
        lblsetImage1 = new javax.swing.JLabel();
        lblRsultPrice = new javax.swing.JLabel();
        lblSetPriceResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(943, 615));
        setResizable(false);

        lblBusca.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblBusca.setText("Buscar produtos");

        txtByName.setText("Buscar por nome");
        txtByName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtByFocusLost(evt);
            }
        });
        txtByName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtByMouseClicked(evt);
            }
        });

        txtByPrice.setText("Buscar por preço");
        txtByPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtByFocusLost(evt);
            }
        });
        txtByPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtByMouseClicked(evt);
            }
        });

        cbByCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Escolha a categoria", "Animais e acessórios", "Músicas e hobbies", "Moda e beleza", "Para a sua casa", "Esportes", "Eletrônicos", "Imóveis","Veículos"}));

        cbBySubCategory.setModel(new DefaultComboBoxModel(DAO.getSubCategory()));

        String[] year = new String[52];
        year[0] = "Ano de aquisição";
        int ano = 1990;

        for(int i = 1; i < 52; i++) {
            year[i] = ano+"";
            ano++;
        }
        cbByYear.setModel(new javax.swing.DefaultComboBoxModel<>(year));

        btnBuscarNome.setText("Ir");
        btnBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscarNome.setActionCommand("Por nome");

        btnBuscarPreco.setText("Ir");
        btnBuscarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscarPreco.setActionCommand("Por preco");

        btnBuscarCategoria.setText("Ir");
        btnBuscarCategoria.setActionCommand("Por categoria");
        btnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarSubcategoria.setText("Ir");
        btnBuscarSubcategoria.setActionCommand("Por subcategoria");
        btnBuscarSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarAno.setText("Ir");
        btnBuscarAno.setActionCommand("Por ano");
        btnBuscarAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblResultado.setText("Resultado");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lstResult.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sem resultados" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstResult);

        lblOBS.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblOBS.setText("* Duplo clique sobre o nome para mais informações");

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblResultNome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblResultNome.setText("Nome");

        lblResultDesc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblResultDesc.setText("Descição");

        lblResultAno.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblResultAno.setText("Ano de aquisição");

        lblResultFotos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblResultFotos.setText("Fotos");

        lblSetNomeResult.setBorder(null);

        txtaSetDescResult.setEditable(false);
        txtaSetDescResult.setBackground(new java.awt.Color(220, 220, 220));
        txtaSetDescResult.setColumns(20);
        txtaSetDescResult.setForeground(new java.awt.Color(76, 76, 76));
        txtaSetDescResult.setLineWrap(true);
        txtaSetDescResult.setRows(5);
        txtaSetDescResult.setWrapStyleWord(true);
        txtaSetDescResult.setBorder(null);
        txtaSetDescResult.setSelectedTextColor(new java.awt.Color(1, 1, 1));
        jScrollPane2.setViewportView(txtaSetDescResult);

        lblRsultPrice.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRsultPrice.setText("Preço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRsultPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResultDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResultNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(lblSetNomeResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSetPriceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(lblSetAnoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblsetImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSetImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblsetImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblResultFotos)
                        .addComponent(lblResultAno)))
                .addGap(23, 23, 23)
                .addComponent(lblSetImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSetNomeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultDesc)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultAno)
                            .addComponent(lblRsultPrice)
                            .addComponent(lblSetPriceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSetAnoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblResultFotos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSetImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsetImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsetImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBusca)
                                .addGap(373, 373, 373))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblResultado)
                                    .addGap(411, 411, 411)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbBySubCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtByName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(cbByYear, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblOBS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBusca)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarNome))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbByYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarAno)
                        .addComponent(btnBuscarCategoria)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPreco)
                    .addComponent(btnBuscarSubcategoria)
                    .addComponent(cbBySubCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOBS))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
       
    private void txtByMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtByMouseClicked
        if(txtByName.hasFocus())
            txtByName.setText("");
        if(txtByPrice.hasFocus())
            txtByPrice.setText("");
    }//GEN-LAST:event_txtByMouseClicked

    private void txtByFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtByFocusLost
        if(txtByName.getText().equals(""))
            txtByName.setText("Buscar por nome");
        if(txtByPrice.getText().equals(""))
            txtByPrice.setText("Buscar por preço");
    }//GEN-LAST:event_txtByFocusLost

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(evt.getActionCommand().equals("Por nome"))
            sql = "SELECT nome, price, description, purchased_year FROM Products WHERE nome LIKE '"+txtByName.getText()+"%'";
        if(evt.getActionCommand().equals("Por preco"))
            sql = "SELECT nome, price, description, purchased_year FROM Products WHERE price = "+txtByPrice.getText();
        if(evt.getActionCommand().equals("Por categoria"))
            if(cbByCategory.getSelectedIndex() != 0)
                sql = "SELECT p.nome, p.price, p.description, p.purchased_year FROM Products p JOIN Category c ON p.id_category = c.id WHERE c.nome LIKE '"+cbByCategory.getSelectedItem()+"'";
        if(evt.getActionCommand().equals("Por subcategoria"))
            if(cbBySubCategory.getSelectedIndex() != 0)
                sql = "SELECT p.nome, p.price, p.description, p.purchased_year FROM Products p JOIN Sub_category sc ON p.id_sub_category = sc.id WHERE sc.nome LIKE'"+cbBySubCategory.getSelectedItem()+"'";
        if(evt.getActionCommand().equals("Por ano"))
            if(cbByYear.getSelectedIndex() != 0)
                sql = "SELECT p.nome, p.price, p.description, p.purchased_year FROM Products p WHERE purchased_year = "+cbByYear.getSelectedItem();
        
      
        if(sql != null) {
            List list = DAO.updateList(sql);
            DML = new DefaultListModel();
                for(int i = 0; i < list.getItemCount(); i++) 
                    DML.addElement(list.getItem(i));
            lstResult.setModel(DML);
        
        }else {
            JOptionPane.showMessageDialog(null, "Campo vazio ou inválido", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        FrmHome frmHome = new FrmHome();
        frmHome.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void lstResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstResultMouseClicked
        if(evt.getClickCount() == 2) {
            String sql1 = "SELECT nome, description, price, purchased_year, image1 FROM Products WHERE nome = \""+lstResult.getSelectedValue()+"\"";
            
            try {
                product = DAO.getData(sql1);
            } catch (FileNotFoundException ex) {
                System.err.println(ex);
            } catch (IOException ex) {
                System.out.println(ex);
            }
            
            lblSetNomeResult.setText(product.getNome());
            txtaSetDescResult.setText(product.getDescription());
            lblSetPriceResult.setText(String.valueOf(product.getPrice()));
            lblSetAnoResult.setText(product.getPurchasedYear());
            
            ImageIcon imgIcon= new ImageIcon(product.getImage1());
            Image im = imgIcon.getImage();
            Image myImg = im.getScaledInstance(97, 97, Image.SCALE_SMOOTH);
            ImageIcon newImage = new ImageIcon(myImg);
            lblsetImage1.setIcon(newImage);
        }
    }//GEN-LAST:event_lstResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSearch frmSearch = new FrmSearch();
                frmSearch.setVisible(true);
                frmSearch.setLocationRelativeTo(null);
                //frmSearch.setExtendedState(FrmSearch.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAno;
    private javax.swing.JButton btnBuscarCategoria;
    private javax.swing.JButton btnBuscarNome;
    private javax.swing.JButton btnBuscarPreco;
    private javax.swing.JButton btnBuscarSubcategoria;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbByCategory;
    private javax.swing.JComboBox<String> cbBySubCategory;
    private javax.swing.JComboBox<String> cbByYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblOBS;
    private javax.swing.JLabel lblResultAno;
    private javax.swing.JLabel lblResultDesc;
    private javax.swing.JLabel lblResultFotos;
    private javax.swing.JLabel lblResultNome;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblRsultPrice;
    private javax.swing.JLabel lblSetAnoResult;
    private javax.swing.JLabel lblSetImage2;
    private javax.swing.JLabel lblSetImage4;
    private javax.swing.JLabel lblSetNomeResult;
    private javax.swing.JLabel lblSetPriceResult;
    private javax.swing.JLabel lblsetImage1;
    private javax.swing.JLabel lblsetImage3;
    private javax.swing.JList<String> lstResult;
    private javax.swing.JTextField txtByName;
    private javax.swing.JTextField txtByPrice;
    private javax.swing.JTextArea txtaSetDescResult;
    // End of variables declaration//GEN-END:variables
}
